name: Run Scrapers

on:
  schedule:
    - cron: "59 * * * *"

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        run: echo "Hello"
